import { useTranslation } from "react-i18next";

const zh = {
  home: "概览",
  apps: "应用接入",
  models: "模型与价格",
  usage: "用量账单",
  help: "连接诊断",
  settings: "设置",
  advanced: "高级工具",
  subtitle: "桌面助手",
  guest: "账户中心",
  accountNote: "查看登录与余额",
  signedInStatus: "已登录野菜API",
  edition: "桌面版",
  theme: "外观",
  light: "浅色",
  dark: "深色",
  system: "跟随系统",
  themeNote: "仅在这台电脑上保存外观偏好。",
  balance: "可用余额",
  spent: "累计消费",
  tokens: "累计用量",
  installed: "已发现应用",
  unit: "个",
  unavailable: "暂不可用",
  localApps: "这台电脑",
  pendingScan: "等待识别",
  failedScan: "暂时无法读取",
  manage: "查看",
  accountAction: "查看账户",
  firstTitle: "选择你想使用的 AI 应用",
  firstBody: "选择应用、线路和模型，确认后助手会自动完成接入。",
  signInFirstTitle: "先登录你的野菜API账户",
  signInFirstBody: "登录后会自动读取余额和可用模型，然后就能一键接入。",
  stepAccount: "登录账户",
  stepApp: "选择应用",
  stepConnect: "完成接入",
  accountPending: "请先登录",
  accountReady: "账户已连接",
  appSection: "我的应用",
  appHint: "本机桌面应用",
  refresh: "重新检查",
  checking: "正在识别",
  version: "应用版本",
  model: "当前模型",
  line: "使用线路",
  notConfigured: "尚未读取",
  notConnected: "连接状态未确认",
  appNotFound: "未发现应用",
  appUnknown: "状态未知",
  viewSetup: "查看接入",
  chooseModel: "选择线路与模型",
  detectedNote: "应用已安装，是否已连接野菜API还需确认。",
  multipleNote: "发现多个安装，尚不能确认要使用哪一个。",
  unsupportedNote: "当前系统尚不支持识别此应用。",
  absentNote: "未发现安装信息，可先了解接入方式。",
  uncertainNote: "暂时不能确认应用状态，请重新检查。",
  loadingNote: "正在查找已安装的应用…",
  moreApps: "使用 Pi、DSH、爱马仕或小龙虾？",
  advancedAction: "查看高级工具",
  recent: "最近消费",
  allBills: "查看账单",
  emptyBills: "暂无账单",
  emptyBillsBody: "此版本暂不支持查看消费记录。",
  privacy: "只修改你确认的应用设置",
  configurationBoundary: "密钥不会显示在界面中",
  accountTitle: "账户充值",
  accountBody: "查看余额、用量和消费记录。",
  accountStatus: "账户功能暂未开放",
  accountStatusBody:
    "此版本暂不支持登录、查询余额和充值。你可以先查看应用和模型，或检查网络连接。",
  noAccountData: "暂无账户数据",
  recharge: "充值暂未开放",
  accountDetails: "登录与密钥安全",
  accountDetailsBody:
    "登录只在野菜API官网完成；桌面端不会读取网站密码，登录状态保存在系统安全存储中。",
  priceTitle: "找到适合你的模型",
  priceBody: "按应用和线路查找模型，查看完整模型 ID。",
  pricePending: "价格暂不可用",
  pricePendingBody:
    "此版本暂不支持价格查询，无法展示官网参考价和你的实际价格。",
  officialPrice: "官网参考价",
  actualPrice: "野菜API实际价",
  priceUnavailable: "暂不可用",
  fx: "对比汇率",
  fxNote: "由野菜API当前设置提供，不参与实际计费。",
  serverFxNote: "来自野菜API当前设置，实际扣费仍以账单为准。",
  selectApp: "使用应用",
  selectLine: "使用线路",
  readinessTitle: "接入准备",
  readinessBody: "选择仅供查看，不会修改应用设置。",
  fullId: "始终显示完整模型 ID",
  lastChecked: "上次检查",
  settingsTitle: "让助手更顺手",
  settingsDescription: "调整外观与语言，查看隐私和版本信息。",
  signIn: "网页登录",
  signInBody:
    "将在浏览器打开野菜API。登录并确认验证码后，桌面端会自动完成登录。",
  authorizationCode: "请核对验证码",
  authorizationWaiting: "等待你在浏览器确认",
  authorizationWaitingBody: "验证码只用于这次登录，请确认网页显示完全一致。",
  cancel: "取消",
  retry: "重试",
  refreshAccount: "刷新数据",
  logout: "退出登录",
  rechargeNow: "去充值",
  signedInAs: "当前账户",
  requestCount: "累计请求",
  observedAt: "更新于",
  mainlandLine: "大陆优化",
  globalLine: "全球加速",
  partialData: "部分数据暂时没有返回，可稍后刷新。",
  accountServerUnavailable: "账户服务尚未上线或当前线路暂不可用。",
  accountNetworkError: "暂时连不上账户服务，请检查网络后重试。",
  accountSessionExpired: "登录已失效，请重新通过网页授权。",
  accountSecureStoreError: "系统安全存储暂不可用，无法保存登录状态。",
  accountAuthorizationDenied: "你已在网页拒绝这次登录。",
  accountAuthorizationExpired: "验证码已过期，请重新发起登录。",
  accountInvalidResponse: "账户数据格式不正确，已停止显示。",
  browserOpenFailed: "浏览器没有自动打开，请重新发起登录。",
  priceSignInRequired: "登录后可查看当前账号可用模型和实际价格。",
  inputPrice: "输入",
  outputPrice: "输出",
  perMillionTokens: "每百万 tokens",
  saveCompared: "比官网参考价低约",
  priceMethodNote: "相同模型、相同输入输出单位；仅完整的倍率计费模型参与比较。",
  availableModels: "你的账户当前可用 {{count}} 个模型",
  accountModels: "账户可用模型",
  setupIntro: "选好应用、线路和模型，助手会为你自动完成配置。",
  setupSafety: "确认前不会修改任何设置",
  setupDone: "已接入",
  readyToConnect: "可以接入",
  yourSelection: "你的选择",
  confirmSetup: "确认接入信息",
  setupSafetyTitle: "密钥会被安全处理",
  setupSafetyBody:
    "密钥只保存在系统安全存储中，应用设置里仅保存安全引用；界面和操作记录都不会显示密钥。",
  setupSuccess: "接入完成",
  setupSuccessBody: "{{app}} 已使用所选模型完成真实回复，现在可以直接使用。",
  setupFailed: "暂时没有完成",
  setupSignedOut: "登录状态已失效，请重新登录后再试。",
  setupModelUnavailable: "这个模型当前不在你的账户可用列表中，请刷新后重选。",
  setupServerUnavailable: "暂时无法从野菜API获取接入信息，请稍后重试。",
  setupWriteFailed: "无法安全更新本机应用设置，原有设置已保留。",
  signInFirst: "先去登录",
  settingUp: "正在接入…",
  setupAgain: "重新写入",
  connectNow: "一键接入",
  viewOtherTools: "查看其他工具",
  openAccount: "查看账户",
};
type Copy = { [K in keyof typeof zh]: string };
const en: Copy = {
  home: "Overview",
  apps: "Applications",
  models: "Models & pricing",
  usage: "Usage & billing",
  help: "Diagnostics",
  settings: "Settings",
  advanced: "Advanced tools",
  subtitle: "Desktop assistant",
  guest: "Account",
  accountNote: "Sign-in, balance & usage",
  signedInStatus: "Signed in to 野菜API",
  edition: "Desktop",
  theme: "Appearance",
  light: "Light",
  dark: "Dark",
  system: "System",
  themeNote: "Appearance preferences stay on this computer.",
  balance: "Available balance",
  spent: "Total spent",
  tokens: "Total tokens",
  installed: "Apps found",
  unit: "apps",
  unavailable: "Unavailable",
  localApps: "On this computer",
  pendingScan: "Waiting for discovery",
  failedScan: "Could not read status",
  manage: "View",
  accountAction: "View account",
  firstTitle: "Choose your AI app",
  firstBody:
    "Choose an app, a connection line and a model, then let the assistant configure it for you.",
  signInFirstTitle: "Sign in to your 野菜API account",
  signInFirstBody:
    "After sign-in, your balance and available models load automatically and one-click setup is ready.",
  stepAccount: "Sign in",
  stepApp: "Choose an app",
  stepConnect: "Connect",
  accountPending: "Sign in first",
  accountReady: "Account connected",
  appSection: "My applications",
  appHint: "Desktop applications",
  refresh: "Check again",
  checking: "Checking",
  version: "App version",
  model: "Current model",
  line: "Connection line",
  notConfigured: "Not read",
  notConnected: "Connection not confirmed",
  appNotFound: "Not found",
  appUnknown: "Status unknown",
  viewSetup: "View setup",
  chooseModel: "Choose line & model",
  detectedNote:
    "App installed. Its connection to 野菜API has not been confirmed.",
  multipleNote:
    "Multiple installations found; the active one is not confirmed.",
  unsupportedNote:
    "Discovery for this application is not supported on this system.",
  absentNote: "No installation found. You can still explore setup.",
  uncertainNote: "Application status could not be confirmed. Try again.",
  loadingNote: "Looking for installed apps…",
  moreApps: "Using Pi, DSH, Hermes or OpenClaw?",
  advancedAction: "View advanced tools",
  recent: "Recent spending",
  allBills: "View billing",
  emptyBills: "No bills available",
  emptyBillsBody: "Spending history is not available in this version.",
  privacy: "Only confirmed app settings are changed",
  configurationBoundary: "Keys never appear in the interface",
  accountTitle: "Add funds",
  accountBody: "Your balance, usage and spending history.",
  accountStatus: "Account features are not available yet",
  accountStatusBody:
    "Sign-in, balance and recharge are not available in this version. You can still explore apps and models or check your connection.",
  noAccountData: "No account data",
  recharge: "Recharge unavailable",
  accountDetails: "Sign-in and credential security",
  accountDetailsBody:
    "Sign-in happens only on the official 野菜API website. The desktop app never reads your website password, and its sign-in state is kept in secure system storage.",
  priceTitle: "Find the model for your app",
  priceBody:
    "Browse models by app and connection line. Full model IDs are shown.",
  pricePending: "Prices unavailable",
  pricePendingBody:
    "This version cannot show official reference prices or your account prices yet.",
  officialPrice: "Official reference",
  actualPrice: "Your 野菜API price",
  priceUnavailable: "Unavailable",
  fx: "Comparison rate",
  fxNote: "Provided by the current 野菜API setting and not used for billing.",
  serverFxNote:
    "From the current 野菜API setting; your bill remains authoritative.",
  selectApp: "Application",
  selectLine: "Connection line",
  readinessTitle: "Connection readiness",
  readinessBody:
    "Selections are for review only and do not change app settings.",
  fullId: "Full model IDs always visible",
  lastChecked: "Last checked",
  settingsTitle: "Make it yours",
  settingsDescription:
    "Choose appearance and language, and review privacy and version details.",
  signIn: "Sign in on the web",
  signInBody:
    "野菜API will open in your browser. Sign in and approve the matching code to finish here automatically.",
  authorizationCode: "Check this code",
  authorizationWaiting: "Waiting for browser approval",
  authorizationWaitingBody:
    "This code is only for this sign-in. Make sure the website shows the same code.",
  cancel: "Cancel",
  retry: "Retry",
  refreshAccount: "Refresh",
  logout: "Sign out",
  rechargeNow: "Add funds",
  signedInAs: "Current account",
  requestCount: "Total requests",
  observedAt: "Updated",
  mainlandLine: "Mainland optimized",
  globalLine: "Global accelerated",
  partialData: "Some data is temporarily unavailable. Try refreshing later.",
  accountServerUnavailable:
    "Account service is not deployed yet or is unavailable on this line.",
  accountNetworkError:
    "Could not reach account service. Check your connection and retry.",
  accountSessionExpired:
    "Your session expired. Authorize again in the browser.",
  accountSecureStoreError:
    "Secure system storage is unavailable, so sign-in cannot be saved.",
  accountAuthorizationDenied: "You declined this sign-in on the website.",
  accountAuthorizationExpired: "The code expired. Start sign-in again.",
  accountInvalidResponse: "Account data was invalid and is not shown.",
  browserOpenFailed: "The browser did not open. Start sign-in again.",
  priceSignInRequired:
    "Sign in to see available models and your account prices.",
  inputPrice: "Input",
  outputPrice: "Output",
  perMillionTokens: "per million tokens",
  saveCompared: "About this much below reference",
  priceMethodNote:
    "Same model and input/output units; only complete ratio-priced models are compared.",
  availableModels: "Your account currently has {{count}} available models",
  accountModels: "Account models",
  setupIntro:
    "Choose an app, line and model. The assistant will configure it for you.",
  setupSafety: "Nothing changes until you confirm",
  setupDone: "Connected",
  readyToConnect: "Ready",
  yourSelection: "Your selection",
  confirmSetup: "Confirm setup",
  setupSafetyTitle: "Your key is handled securely",
  setupSafetyBody:
    "The key stays in secure system storage. Application settings contain only a safe reference, and the key never appears in the interface or activity history.",
  setupSuccess: "Connection complete",
  setupSuccessBody:
    "{{app}} completed a real response with the selected model and is ready to use.",
  setupFailed: "Setup not completed",
  setupSignedOut: "Your sign-in expired. Sign in again and retry.",
  setupModelUnavailable:
    "This model is no longer available to your account. Refresh and choose another.",
  setupServerUnavailable:
    "Could not retrieve setup information from 野菜API. Try again shortly.",
  setupWriteFailed:
    "The app settings could not be updated safely. Existing settings were preserved.",
  signInFirst: "Sign in first",
  settingUp: "Setting up…",
  setupAgain: "Write again",
  connectNow: "One-click setup",
  viewOtherTools: "Other tools",
  openAccount: "View account",
};
const tw: Copy = {
  home: "概覽",
  apps: "應用接入",
  models: "模型與價格",
  usage: "用量帳單",
  help: "連線診斷",
  settings: "設定",
  advanced: "進階工具",
  subtitle: "桌面助手",
  guest: "帳戶中心",
  accountNote: "查看登入、餘額與用量",
  signedInStatus: "已登入野菜API",
  edition: "桌面版",
  theme: "外觀",
  light: "淺色",
  dark: "深色",
  system: "跟隨系統",
  themeNote: "僅在這台電腦上儲存外觀偏好。",
  balance: "可用餘額",
  spent: "累計消費",
  tokens: "累計用量",
  installed: "已發現應用",
  unit: "个",
  unavailable: "暫不可用",
  localApps: "這台電腦",
  pendingScan: "等待識別",
  failedScan: "暫時無法讀取",
  manage: "查看",
  accountAction: "查看帳戶",
  firstTitle: "選擇你想使用的 AI 應用",
  firstBody: "選擇應用、線路和模型，確認後助手會自動完成接入。",
  signInFirstTitle: "先登入你的野菜API帳戶",
  signInFirstBody: "登入後會自動讀取餘額和可用模型，然後就能一鍵接入。",
  stepAccount: "登入帳戶",
  stepApp: "選擇應用",
  stepConnect: "完成接入",
  accountPending: "請先登入",
  accountReady: "帳戶已連線",
  appSection: "我的應用",
  appHint: "本機桌面應用",
  refresh: "重新檢查",
  checking: "正在識別",
  version: "應用版本",
  model: "目前模型",
  line: "使用線路",
  notConfigured: "尚未讀取",
  notConnected: "連線狀態未確認",
  appNotFound: "未發現應用",
  appUnknown: "狀態未知",
  viewSetup: "查看接入",
  chooseModel: "選擇線路與模型",
  detectedNote: "應用已安裝，是否已連線野菜API還需確認。",
  multipleNote: "發現多個安裝，尚不能確認要使用哪一個。",
  unsupportedNote: "目前系統尚不支援識別此應用。",
  absentNote: "未發現安裝資訊，可先了解接入方式。",
  uncertainNote: "暫時不能確認應用狀態，請重新檢查。",
  loadingNote: "正在尋找已安裝的應用…",
  moreApps: "使用 Pi、DSH、Hermes 或 OpenClaw？",
  advancedAction: "查看進階工具",
  recent: "最近消費",
  allBills: "查看帳單",
  emptyBills: "暫無帳單",
  emptyBillsBody: "此版本暫不支援查看消費記錄。",
  privacy: "只修改你確認的應用設定",
  configurationBoundary: "金鑰不會顯示在介面中",
  accountTitle: "帳戶儲值",
  accountBody: "查看餘額、用量和消費記錄。",
  accountStatus: "帳戶功能暫未開放",
  accountStatusBody:
    "此版本暫不支援登入、查詢餘額和儲值。你可以先查看應用和模型，或檢查網路連線。",
  noAccountData: "暫無帳戶資料",
  recharge: "儲值暫未開放",
  accountDetails: "登入與憑證安全",
  accountDetailsBody:
    "登入只在野菜API官網完成；桌面端不會讀取網站密碼，登入狀態會儲存在系統安全儲存空間。",
  priceTitle: "找到適合你的模型",
  priceBody: "按應用和線路尋找模型，查看完整模型 ID。",
  pricePending: "價格暫不可用",
  pricePendingBody:
    "此版本暫不支援價格查詢，無法展示官網參考價和你的實際價格。",
  officialPrice: "官網參考價",
  actualPrice: "野菜API實際價",
  priceUnavailable: "暫不可用",
  fx: "對比匯率",
  fxNote: "由野菜API目前設定提供，不參與實際計費。",
  serverFxNote: "來自野菜API目前設定，實際扣費仍以帳單為準。",
  selectApp: "使用應用",
  selectLine: "使用線路",
  readinessTitle: "接入準備",
  readinessBody: "選擇僅供查看，不會修改應用設定。",
  fullId: "始終顯示完整模型 ID",
  lastChecked: "上次檢查",
  settingsTitle: "讓助手更順手",
  settingsDescription: "調整外觀與語言，查看隱私和版本資訊。",
  signIn: "網頁登入",
  signInBody:
    "將在瀏覽器開啟野菜API。登入並確認驗證碼後，桌面端會自動完成登入。",
  authorizationCode: "請核對驗證碼",
  authorizationWaiting: "等待你在瀏覽器確認",
  authorizationWaitingBody: "驗證碼只用於這次登入，請確認網頁顯示完全一致。",
  cancel: "取消",
  retry: "重試",
  refreshAccount: "重新整理資料",
  logout: "登出",
  rechargeNow: "去儲值",
  signedInAs: "目前帳戶",
  requestCount: "累計請求",
  observedAt: "更新於",
  mainlandLine: "大陸最佳化",
  globalLine: "全球加速",
  partialData: "部分資料暫時沒有返回，可稍後重新整理。",
  accountServerUnavailable: "帳戶服務尚未上線或目前線路暫不可用。",
  accountNetworkError: "暫時連不上帳戶服務，請檢查網路後重試。",
  accountSessionExpired: "登入已失效，請重新透過網頁授權。",
  accountSecureStoreError: "系統安全儲存暫不可用，無法儲存登入狀態。",
  accountAuthorizationDenied: "你已在網頁拒絕這次登入。",
  accountAuthorizationExpired: "驗證碼已過期，請重新發起登入。",
  accountInvalidResponse: "帳戶資料格式不正確，已停止顯示。",
  browserOpenFailed: "瀏覽器沒有自動開啟，請重新發起登入。",
  priceSignInRequired: "登入後可查看目前帳戶可用模型和實際價格。",
  inputPrice: "輸入",
  outputPrice: "輸出",
  perMillionTokens: "每百萬 tokens",
  saveCompared: "比官網參考價低約",
  priceMethodNote: "相同模型、相同輸入輸出單位；僅完整的倍率計費模型參與比較。",
  availableModels: "你的帳戶目前可用 {{count}} 個模型",
  accountModels: "帳戶可用模型",
  setupIntro: "選好應用、線路和模型，助手會為你自動完成設定。",
  setupSafety: "確認前不會修改任何設定",
  setupDone: "已接入",
  readyToConnect: "可以接入",
  yourSelection: "你的選擇",
  confirmSetup: "確認接入資訊",
  setupSafetyTitle: "金鑰會被安全處理",
  setupSafetyBody:
    "金鑰只會儲存在系統安全儲存空間，應用設定僅保留安全引用；介面和操作記錄都不會顯示金鑰。",
  setupSuccess: "接入完成",
  setupSuccessBody: "{{app}} 已使用所選模型完成真實回覆，現在可以直接使用。",
  setupFailed: "暫時沒有完成",
  setupSignedOut: "登入狀態已失效，請重新登入後再試。",
  setupModelUnavailable:
    "這個模型目前不在你的帳戶可用清單中，請重新整理後重選。",
  setupServerUnavailable: "暫時無法從野菜API取得接入資訊，請稍後重試。",
  setupWriteFailed: "無法安全更新本機應用設定，原有設定已保留。",
  signInFirst: "先去登入",
  settingUp: "正在接入…",
  setupAgain: "重新寫入",
  connectNow: "一鍵接入",
  viewOtherTools: "查看其他工具",
  openAccount: "查看帳戶",
};
const ja: Copy = {
  home: "概要",
  apps: "アプリ接続",
  models: "モデルと料金",
  usage: "使用量と請求",
  help: "接続診断",
  settings: "設定",
  advanced: "高度なツール",
  subtitle: "デスクトップアシスタント",
  guest: "アカウント",
  accountNote: "ログイン・残高・使用量",
  signedInStatus: "野菜APIにログイン済み",
  edition: "デスクトップ版",
  theme: "外観",
  light: "ライト",
  dark: "ダーク",
  system: "システム",
  themeNote: "外観の設定はこの端末にのみ保存します。",
  balance: "利用可能残高",
  spent: "累計料金",
  tokens: "累計使用量",
  installed: "検出したアプリ",
  unit: "件",
  unavailable: "現在利用できません",
  localApps: "この端末",
  pendingScan: "検出待ち",
  failedScan: "状態を取得できません",
  manage: "表示",
  accountAction: "アカウントを見る",
  firstTitle: "使いたい AI アプリを選ぶ",
  firstBody: "アプリ、回線、モデルを選ぶと、アシスタントが自動で設定します。",
  signInFirstTitle: "野菜APIアカウントにログイン",
  signInFirstBody:
    "ログイン後に残高と利用可能なモデルを自動取得し、ワンクリック設定を利用できます。",
  stepAccount: "ログイン",
  stepApp: "アプリを選択",
  stepConnect: "接続完了",
  accountPending: "先にログイン",
  accountReady: "アカウント接続済み",
  appSection: "マイアプリ",
  appHint: "デスクトップアプリ",
  refresh: "再確認",
  checking: "確認中",
  version: "アプリバージョン",
  model: "現在のモデル",
  line: "使用回線",
  notConfigured: "未取得",
  notConnected: "接続は未確認",
  appNotFound: "未検出",
  appUnknown: "状態不明",
  viewSetup: "接続方法を見る",
  chooseModel: "回線とモデルを選択",
  detectedNote: "インストール済みです。野菜API への接続は未確認です。",
  multipleNote: "複数のインストールを検出しました。使用するものは未確認です。",
  unsupportedNote: "このシステムではこのアプリの検出に対応していません。",
  absentNote: "インストール情報がありません。接続方法は確認できます。",
  uncertainNote: "アプリの状態を確認できません。再試行してください。",
  loadingNote: "インストール済みアプリを探しています…",
  moreApps: "Pi・DSH・Hermes・OpenClaw をお使いですか？",
  advancedAction: "高度なツールを見る",
  recent: "最近の料金",
  allBills: "請求を見る",
  emptyBills: "請求情報はありません",
  emptyBillsBody: "このバージョンでは利用明細を確認できません。",
  privacy: "確認したアプリ設定だけを変更します",
  configurationBoundary: "キーは画面に表示されません",
  accountTitle: "残高をチャージ",
  accountBody: "残高、使用量、利用明細を確認できます。",
  accountStatus: "アカウント機能は準備中",
  accountStatusBody:
    "このバージョンではログイン、残高確認、チャージはできません。アプリやモデルの確認、接続チェックは利用できます。",
  noAccountData: "アカウントデータなし",
  recharge: "チャージは未対応",
  accountDetails: "ログインと認証情報の保護",
  accountDetailsBody:
    "ログインは野菜API公式サイトでのみ行います。デスクトップアプリはWebサイトのパスワードを読み取らず、ログイン状態はOSの安全な保存領域に保管します。",
  priceTitle: "アプリに合うモデルを選ぶ",
  priceBody:
    "アプリと回線ごとにモデルを探せます。モデル ID は省略せず表示します。",
  pricePending: "料金は現在表示できません",
  pricePendingBody:
    "このバージョンでは公式参考価格とご利用料金を確認できません。",
  officialPrice: "公式参考価格",
  actualPrice: "野菜API実際の料金",
  priceUnavailable: "現在利用できません",
  fx: "比較用為替レート",
  fxNote: "現在の野菜API設定から取得し、実際の課金には使用しません。",
  serverFxNote: "現在の野菜API設定から取得します。実際の請求は明細が基準です。",
  selectApp: "使用するアプリ",
  selectLine: "使用する回線",
  readinessTitle: "接続準備",
  readinessBody: "選択内容の確認のみで、アプリの設定は変更しません。",
  fullId: "完全なモデル ID を表示",
  lastChecked: "最終確認",
  settingsTitle: "使いやすくカスタマイズ",
  settingsDescription:
    "外観と言語を選び、プライバシーとバージョンを確認できます。",
  signIn: "Web でログイン",
  signInBody:
    "ブラウザで野菜APIを開きます。ログインして同じコードを承認すると、自動的に完了します。",
  authorizationCode: "コードを確認",
  authorizationWaiting: "ブラウザでの承認待ち",
  authorizationWaitingBody:
    "このコードは今回のログイン専用です。Webサイトと一致することを確認してください。",
  cancel: "キャンセル",
  retry: "再試行",
  refreshAccount: "更新",
  logout: "ログアウト",
  rechargeNow: "チャージ",
  signedInAs: "現在のアカウント",
  requestCount: "累計リクエスト",
  observedAt: "更新",
  mainlandLine: "中国本土最適化",
  globalLine: "グローバル加速",
  partialData:
    "一部のデータを取得できませんでした。後でもう一度お試しください。",
  accountServerUnavailable:
    "アカウントサービスは未公開か、この回線では利用できません。",
  accountNetworkError:
    "アカウントサービスに接続できません。ネットワークを確認してください。",
  accountSessionExpired:
    "ログインの有効期限が切れました。ブラウザで再認証してください。",
  accountSecureStoreError:
    "システムの安全な保存領域を利用できないため、ログインを保存できません。",
  accountAuthorizationDenied: "Webサイトで今回のログインを拒否しました。",
  accountAuthorizationExpired:
    "コードの有効期限が切れました。もう一度ログインしてください。",
  accountInvalidResponse: "アカウントデータが不正なため表示を停止しました。",
  browserOpenFailed:
    "ブラウザを開けませんでした。もう一度ログインしてください。",
  priceSignInRequired:
    "ログインすると利用可能なモデルとアカウント料金を確認できます。",
  inputPrice: "入力",
  outputPrice: "出力",
  perMillionTokens: "100万 tokens あたり",
  saveCompared: "参考価格より約",
  priceMethodNote:
    "同じモデル・同じ入出力単位で、完全な倍率課金モデルのみ比較します。",
  availableModels: "アカウントで現在 {{count}} 個のモデルを利用できます",
  accountModels: "アカウントのモデル",
  setupIntro: "アプリ、回線、モデルを選ぶと、アシスタントが自動で設定します。",
  setupSafety: "確認するまで設定は変更されません",
  setupDone: "接続済み",
  readyToConnect: "設定可能",
  yourSelection: "選択内容",
  confirmSetup: "接続内容を確認",
  setupSafetyTitle: "キーは安全に処理されます",
  setupSafetyBody:
    "キーはOSの安全な保存領域にのみ保管され、アプリ設定には安全な参照だけが残ります。画面や操作履歴には表示されません。",
  setupSuccess: "接続が完了しました",
  setupSuccessBody:
    "{{app}} は選択したモデルで実際の応答を完了し、そのまま利用できます。",
  setupFailed: "接続できませんでした",
  setupSignedOut: "ログインの有効期限が切れました。再度ログインしてください。",
  setupModelUnavailable:
    "このモデルは現在アカウントで利用できません。更新して選び直してください。",
  setupServerUnavailable:
    "野菜APIから接続情報を取得できません。しばらくしてから再試行してください。",
  setupWriteFailed:
    "アプリ設定を安全に更新できませんでした。既存設定は保持されています。",
  signInFirst: "先にログイン",
  settingUp: "設定中…",
  setupAgain: "もう一度書き込む",
  connectNow: "ワンクリック設定",
  viewOtherTools: "その他のツール",
  openAccount: "アカウントを見る",
};
export const workbenchCopies = { zh, "zh-TW": tw, en, ja };
export function useWorkbenchCopy(): Copy {
  const { i18n } = useTranslation();
  const lang = i18n.resolvedLanguage ?? i18n.language;
  return (
    workbenchCopies[lang as keyof typeof workbenchCopies] ??
    (lang?.startsWith("zh") ? zh : en)
  );
}
