import { useTranslation } from "react-i18next";

const zh = {
  home: "概览",
  apps: "应用接入",
  models: "模型与价格",
  usage: "用量账单",
  help: "连接诊断",
  settings: "设置",
  advanced: "高级工具",
  subtitle: "桌面助手",
  guest: "未登录",
  accountNote: "登录暂未开放",
  edition: "测试版",
  theme: "外观",
  light: "浅色",
  dark: "深色",
  system: "跟随系统",
  themeNote: "仅在这台电脑上保存外观偏好。",
  balance: "可用余额",
  spent: "今日消费",
  tokens: "今日用量",
  installed: "已发现应用",
  unit: "个",
  unavailable: "暂不可用",
  localApps: "这台电脑",
  pendingScan: "等待识别",
  failedScan: "暂时无法读取",
  manage: "查看",
  accountAction: "查看账户",
  firstTitle: "选择你想使用的 AI 应用",
  firstBody:
    "先选应用，再选线路和模型。一键接入暂未开放，你可以先看看有哪些选择。",
  stepAccount: "登录账户",
  stepApp: "选择应用",
  stepConnect: "完成接入",
  accountPending: "登录暂未开放",
  appSection: "我的应用",
  appHint: "本机桌面应用",
  refresh: "重新检查",
  checking: "正在识别",
  version: "应用版本",
  model: "当前模型",
  line: "使用线路",
  notConfigured: "尚未读取",
  notConnected: "连接状态未确认",
  appNotFound: "未发现应用",
  appUnknown: "状态未知",
  viewSetup: "查看接入",
  chooseModel: "选择线路与模型",
  detectedNote: "应用已安装，是否已连接野菜API还需确认。",
  multipleNote: "发现多个安装，尚不能确认要使用哪一个。",
  unsupportedNote: "当前系统尚不支持识别此应用。",
  absentNote: "未发现安装信息，可先了解接入方式。",
  uncertainNote: "暂时不能确认应用状态，请重新检查。",
  loadingNote: "正在查找已安装的应用…",
  moreApps: "使用 OpenCode、Pi 或 DSH？",
  advancedAction: "查看高级工具",
  recent: "最近消费",
  allBills: "查看账单",
  emptyBills: "暂无账单",
  emptyBillsBody: "此版本暂不支持查看消费记录。",
  privacy: "不会修改你的应用设置",
  configurationBoundary: "一键接入暂未开放",
  accountTitle: "账户充值",
  accountBody: "查看余额、用量和消费记录。",
  accountStatus: "账户功能暂未开放",
  accountStatusBody:
    "此版本暂不支持登录、查询余额和充值。你可以先查看应用和模型，或检查网络连接。",
  noAccountData: "暂无账户数据",
  recharge: "充值暂未开放",
  accountDetails: "为什么暂时不可用？",
  accountDetailsBody:
    "账户功能还在准备中。现在不需要在这里输入网站密码或登录信息。",
  priceTitle: "找到适合你的模型",
  priceBody: "按应用和线路查找模型，查看完整模型 ID。",
  pricePending: "价格暂不可用",
  pricePendingBody:
    "此版本暂不支持价格查询，无法展示官网参考价和你的实际价格。",
  officialPrice: "官网参考价",
  actualPrice: "野菜API实际价",
  priceUnavailable: "暂不可用",
  fx: "对比汇率",
  fxNote: "固定展示汇率，不参与实际计费。",
  selectApp: "使用应用",
  selectLine: "使用线路",
  readinessTitle: "接入准备",
  readinessBody: "选择仅供查看，不会修改应用设置。",
  fullId: "始终显示完整模型 ID",
  lastChecked: "上次检查",
  settingsTitle: "让助手更顺手",
  settingsDescription: "调整外观与语言，查看隐私和版本信息。",
};
type Copy = { [K in keyof typeof zh]: string };
const en: Copy = {
  home: "Overview",
  apps: "Applications",
  models: "Models & pricing",
  usage: "Usage & billing",
  help: "Diagnostics",
  settings: "Settings",
  advanced: "Advanced tools",
  subtitle: "Desktop assistant",
  guest: "Not signed in",
  accountNote: "Sign-in unavailable",
  edition: "Test version",
  theme: "Appearance",
  light: "Light",
  dark: "Dark",
  system: "System",
  themeNote: "Appearance preferences stay on this computer.",
  balance: "Available balance",
  spent: "Spent today",
  tokens: "Tokens today",
  installed: "Apps found",
  unit: "apps",
  unavailable: "Unavailable",
  localApps: "On this computer",
  pendingScan: "Waiting for discovery",
  failedScan: "Could not read status",
  manage: "View",
  accountAction: "View account",
  firstTitle: "Choose your AI app",
  firstBody:
    "Choose an app, a connection line and a model. One-click setup is not available yet, but you can explore your options.",
  stepAccount: "Sign in",
  stepApp: "Choose an app",
  stepConnect: "Connect",
  accountPending: "Sign-in unavailable",
  appSection: "My applications",
  appHint: "Desktop applications",
  refresh: "Check again",
  checking: "Checking",
  version: "App version",
  model: "Current model",
  line: "Connection line",
  notConfigured: "Not read",
  notConnected: "Connection not confirmed",
  appNotFound: "Not found",
  appUnknown: "Status unknown",
  viewSetup: "View setup",
  chooseModel: "Choose line & model",
  detectedNote:
    "App installed. Its connection to 野菜API has not been confirmed.",
  multipleNote:
    "Multiple installations found; the active one is not confirmed.",
  unsupportedNote:
    "Discovery for this application is not supported on this system.",
  absentNote: "No installation found. You can still explore setup.",
  uncertainNote: "Application status could not be confirmed. Try again.",
  loadingNote: "Looking for installed apps…",
  moreApps: "Using OpenCode, Pi or DSH?",
  advancedAction: "View advanced tools",
  recent: "Recent spending",
  allBills: "View billing",
  emptyBills: "No bills available",
  emptyBillsBody: "Spending history is not available in this version.",
  privacy: "Your app settings stay unchanged",
  configurationBoundary: "One-click setup is not available yet",
  accountTitle: "Add funds",
  accountBody: "Your balance, usage and spending history.",
  accountStatus: "Account features are not available yet",
  accountStatusBody:
    "Sign-in, balance and recharge are not available in this version. You can still explore apps and models or check your connection.",
  noAccountData: "No account data",
  recharge: "Recharge unavailable",
  accountDetails: "Why is this unavailable?",
  accountDetailsBody:
    "Account features are still being prepared. You do not need to enter website passwords or sign-in details here.",
  priceTitle: "Find the model for your app",
  priceBody:
    "Browse models by app and connection line. Full model IDs are shown.",
  pricePending: "Prices unavailable",
  pricePendingBody:
    "This version cannot show official reference prices or your account prices yet.",
  officialPrice: "Official reference",
  actualPrice: "Your 野菜API price",
  priceUnavailable: "Unavailable",
  fx: "Comparison rate",
  fxNote: "Fixed display rate, not used for billing.",
  selectApp: "Application",
  selectLine: "Connection line",
  readinessTitle: "Connection readiness",
  readinessBody:
    "Selections are for review only and do not change app settings.",
  fullId: "Full model IDs always visible",
  lastChecked: "Last checked",
  settingsTitle: "Make it yours",
  settingsDescription:
    "Choose appearance and language, and review privacy and version details.",
};
const tw: Copy = {
  home: "概覽",
  apps: "應用接入",
  models: "模型與價格",
  usage: "用量帳單",
  help: "連線診斷",
  settings: "設定",
  advanced: "進階工具",
  subtitle: "桌面助手",
  guest: "未登入",
  accountNote: "登入暫未開放",
  edition: "測試版",
  theme: "外觀",
  light: "淺色",
  dark: "深色",
  system: "跟隨系統",
  themeNote: "僅在這台電腦上儲存外觀偏好。",
  balance: "可用餘額",
  spent: "今日消費",
  tokens: "今日用量",
  installed: "已發現應用",
  unit: "个",
  unavailable: "暫不可用",
  localApps: "這台電腦",
  pendingScan: "等待識別",
  failedScan: "暫時無法讀取",
  manage: "查看",
  accountAction: "查看帳戶",
  firstTitle: "選擇你想使用的 AI 應用",
  firstBody:
    "先選應用，再選線路和模型。一鍵接入暫未開放，你可以先看看有哪些選擇。",
  stepAccount: "登入帳戶",
  stepApp: "選擇應用",
  stepConnect: "完成接入",
  accountPending: "登入暫未開放",
  appSection: "我的應用",
  appHint: "本機桌面應用",
  refresh: "重新檢查",
  checking: "正在識別",
  version: "應用版本",
  model: "目前模型",
  line: "使用線路",
  notConfigured: "尚未讀取",
  notConnected: "連線狀態未確認",
  appNotFound: "未發現應用",
  appUnknown: "狀態未知",
  viewSetup: "查看接入",
  chooseModel: "選擇線路與模型",
  detectedNote: "應用已安裝，是否已連線野菜API還需確認。",
  multipleNote: "發現多個安裝，尚不能確認要使用哪一個。",
  unsupportedNote: "目前系統尚不支援識別此應用。",
  absentNote: "未發現安裝資訊，可先了解接入方式。",
  uncertainNote: "暫時不能確認應用狀態，請重新檢查。",
  loadingNote: "正在尋找已安裝的應用…",
  moreApps: "使用 OpenCode、Pi 或 DSH？",
  advancedAction: "查看進階工具",
  recent: "最近消費",
  allBills: "查看帳單",
  emptyBills: "暫無帳單",
  emptyBillsBody: "此版本暫不支援查看消費記錄。",
  privacy: "不會修改你的應用設定",
  configurationBoundary: "一鍵接入暫未開放",
  accountTitle: "帳戶儲值",
  accountBody: "查看餘額、用量和消費記錄。",
  accountStatus: "帳戶功能暫未開放",
  accountStatusBody:
    "此版本暫不支援登入、查詢餘額和儲值。你可以先查看應用和模型，或檢查網路連線。",
  noAccountData: "暫無帳戶資料",
  recharge: "儲值暫未開放",
  accountDetails: "為什麼暫時不可用？",
  accountDetailsBody:
    "帳戶功能還在準備中。現在不需要在這裡輸入網站密碼或登入資訊。",
  priceTitle: "找到適合你的模型",
  priceBody: "按應用和線路尋找模型，查看完整模型 ID。",
  pricePending: "價格暫不可用",
  pricePendingBody:
    "此版本暫不支援價格查詢，無法展示官網參考價和你的實際價格。",
  officialPrice: "官網參考價",
  actualPrice: "野菜API實際價",
  priceUnavailable: "暫不可用",
  fx: "對比匯率",
  fxNote: "固定展示匯率，不參與實際計費。",
  selectApp: "使用應用",
  selectLine: "使用線路",
  readinessTitle: "接入準備",
  readinessBody: "選擇僅供查看，不會修改應用設定。",
  fullId: "始終顯示完整模型 ID",
  lastChecked: "上次檢查",
  settingsTitle: "讓助手更順手",
  settingsDescription: "調整外觀與語言，查看隱私和版本資訊。",
};
const ja: Copy = {
  home: "概要",
  apps: "アプリ接続",
  models: "モデルと料金",
  usage: "使用量と請求",
  help: "接続診断",
  settings: "設定",
  advanced: "高度なツール",
  subtitle: "デスクトップアシスタント",
  guest: "未ログイン",
  accountNote: "ログインは準備中",
  edition: "テスト版",
  theme: "外観",
  light: "ライト",
  dark: "ダーク",
  system: "システム",
  themeNote: "外観の設定はこの端末にのみ保存します。",
  balance: "利用可能残高",
  spent: "今日の料金",
  tokens: "今日の使用量",
  installed: "検出したアプリ",
  unit: "件",
  unavailable: "現在利用できません",
  localApps: "この端末",
  pendingScan: "検出待ち",
  failedScan: "状態を取得できません",
  manage: "表示",
  accountAction: "アカウントを見る",
  firstTitle: "使いたい AI アプリを選ぶ",
  firstBody:
    "アプリ、回線、モデルを選べます。ワンクリック設定はまだ利用できません。",
  stepAccount: "ログイン",
  stepApp: "アプリを選択",
  stepConnect: "接続完了",
  accountPending: "ログインは準備中",
  appSection: "マイアプリ",
  appHint: "デスクトップアプリ",
  refresh: "再確認",
  checking: "確認中",
  version: "アプリバージョン",
  model: "現在のモデル",
  line: "使用回線",
  notConfigured: "未取得",
  notConnected: "接続は未確認",
  appNotFound: "未検出",
  appUnknown: "状態不明",
  viewSetup: "接続方法を見る",
  chooseModel: "回線とモデルを選択",
  detectedNote: "インストール済みです。野菜API への接続は未確認です。",
  multipleNote: "複数のインストールを検出しました。使用するものは未確認です。",
  unsupportedNote: "このシステムではこのアプリの検出に対応していません。",
  absentNote: "インストール情報がありません。接続方法は確認できます。",
  uncertainNote: "アプリの状態を確認できません。再試行してください。",
  loadingNote: "インストール済みアプリを探しています…",
  moreApps: "OpenCode・Pi・DSH をお使いですか？",
  advancedAction: "高度なツールを見る",
  recent: "最近の料金",
  allBills: "請求を見る",
  emptyBills: "請求情報はありません",
  emptyBillsBody: "このバージョンでは利用明細を確認できません。",
  privacy: "アプリの設定は変更しません",
  configurationBoundary: "ワンクリック設定は準備中",
  accountTitle: "残高をチャージ",
  accountBody: "残高、使用量、利用明細を確認できます。",
  accountStatus: "アカウント機能は準備中",
  accountStatusBody:
    "このバージョンではログイン、残高確認、チャージはできません。アプリやモデルの確認、接続チェックは利用できます。",
  noAccountData: "アカウントデータなし",
  recharge: "チャージは未対応",
  accountDetails: "利用できない理由",
  accountDetailsBody:
    "アカウント機能は準備中です。ここにパスワードやログイン情報を入力する必要はありません。",
  priceTitle: "アプリに合うモデルを選ぶ",
  priceBody:
    "アプリと回線ごとにモデルを探せます。モデル ID は省略せず表示します。",
  pricePending: "料金は現在表示できません",
  pricePendingBody:
    "このバージョンでは公式参考価格とご利用料金を確認できません。",
  officialPrice: "公式参考価格",
  actualPrice: "野菜API実際の料金",
  priceUnavailable: "現在利用できません",
  fx: "比較用為替レート",
  fxNote: "表示専用の固定レート。課金には使用しません。",
  selectApp: "使用するアプリ",
  selectLine: "使用する回線",
  readinessTitle: "接続準備",
  readinessBody: "選択内容の確認のみで、アプリの設定は変更しません。",
  fullId: "完全なモデル ID を表示",
  lastChecked: "最終確認",
  settingsTitle: "使いやすくカスタマイズ",
  settingsDescription:
    "外観と言語を選び、プライバシーとバージョンを確認できます。",
};
export const workbenchCopies = { zh, "zh-TW": tw, en, ja };
export function useWorkbenchCopy(): Copy {
  const { i18n } = useTranslation();
  const lang = i18n.resolvedLanguage ?? i18n.language;
  return (
    workbenchCopies[lang as keyof typeof workbenchCopies] ??
    (lang?.startsWith("zh") ? zh : en)
  );
}
