import { useTranslation } from "react-i18next";

const zh = {
  title: "这笔用量，省了多少",
  official: "官网同用量估算",
  actual: "野菜实际扣费",
  saved: "预计节省",
  more: "高于官网估算",
  same: "与官网估算持平",
  unavailable: "暂未接通账单",
  unavailableBody:
    "账单接通后，这里会按相同模型和用量对比费用。现在还没有可核对的数据。",
  invalid: "暂时无法核对费用",
  invalidBody: "这份费用明细不完整或金额不一致，暂不展示比较结果。",
  expired: "费用信息已过期",
  expiredBody: "需要重新获取账单后，才能继续展示费用对比。",
  none: "暂无可比较的用量",
  noneBody: "所选范围内还没有资料完整的已结算记录。",
  method: "怎么算的",
  methodBody:
    "使用同一笔用量当时的官网 API 价格，分别计算输入、输出和缓存费用，再与野菜账单的最终扣费比较。美元参考价按 6.75 折算，实际扣费不重复换算。",
  estimate:
    "官网金额为相同模型、用量及缓存条件下的估算，不是官网实际账单。实际扣费指余额扣减，不等同于充值时支付的现金。",
  missing: "资料不足的用量不计入节省金额；套餐、赠送及其他计费方式需单独核对。",
  coverage: "已纳入",
  requests: "笔",
  excluded: "未纳入比较的扣费",
  pending: "尚有待结算记录",
  details: "逐笔明细",
  request: "记录编号",
  requestedAt: "使用时间",
  rounding:
    "分项费用及每笔美元换算先四舍五入到小数点后 6 位，再汇总；页面金额保留 2 位。节省比例 =（官网估算 − 实际扣费）÷ 官网估算，使用未取整的汇总金额计算。",
  source: "官网来源",
  version: "价格版本",
  fxVersion: "汇率版本",
  model: "模型 ID",
  officialModel: "官网模型",
  conditions: "适用条件",
  qty: "用量",
  rate: "每百万 token 单价",
  amount: "官网分项费用",
  total: "官网原币合计",
  currency: "币种",
  period: "统计范围（本机时区）",
  to: "至",
  effective: "价格生效时间",
  checked: "价格核对时间",
  input: "普通输入",
  output: "输出",
  cache_read: "缓存读取",
  cache_write_5m: "缓存写入 · 5 分钟",
  cache_write_1h: "缓存写入 · 1 小时",
  missing_usage: "缺少完整用量",
  model_unverified: "模型尚无法对应",
  unsupported_billing: "该计费方式尚未支持对比",
  pending_settlement: "结算中",
  missing_price_history: "缺少当时的官网价格",
  unsupported_funding: "需要单独核对资金来源",
};
type Copy = { [K in keyof typeof zh]: string };
const en: Copy = {
  title: "Your usage, compared",
  official: "Estimated official cost",
  actual: "Actual 野菜API charge",
  saved: "Estimated savings",
  more: "Above the official estimate",
  same: "Same as the official estimate",
  unavailable: "Billing is not connected",
  unavailableBody:
    "Once billing is connected, compare the same models and usage here. There is no bill to verify yet.",
  invalid: "Unable to verify these costs",
  invalidBody:
    "Details are incomplete or amounts do not match. No comparison is shown.",
  expired: "Cost information has expired",
  expiredBody: "Fetch a current bill before displaying this comparison again.",
  none: "No comparable usage yet",
  noneBody: "This period has no settled records with complete pricing details.",
  method: "How is this calculated?",
  methodBody:
    "Price the same request using the official API rates effective at the time, separating input, output and cache. Compare it with the final ledger charge. USD reference prices use a fixed 6.75 conversion; your charge is not converted again.",
  estimate:
    "Official costs assume the same model, usage and cache conditions; they are not an actual provider invoice. Charges mean balance deductions, not cash paid when adding funds.",
  missing:
    "Incomplete records are excluded from savings. Plans, gifted credit and other billing methods require separate reconciliation.",
  coverage: "Included",
  requests: "requests",
  excluded: "Known charges excluded from comparison",
  pending: "Some records are still settling",
  details: "Request details",
  request: "Record ID",
  requestedAt: "Usage time",
  rounding:
    "Round each line and each request's USD conversion half-up to 6 decimal places, then sum. Display totals to 2 decimals. Savings rate = (official estimate − actual charge) ÷ official estimate, using totals before display rounding.",
  source: "Official source",
  version: "Price version",
  fxVersion: "Exchange-rate version",
  model: "Model ID",
  officialModel: "Official model",
  conditions: "Applicable conditions",
  qty: "Usage",
  rate: "Price per million tokens",
  amount: "Official line cost",
  total: "Official total in source currency",
  currency: "Currency",
  period: "Period (local time)",
  to: "to",
  effective: "Price effective from",
  checked: "Price checked at",
  input: "Uncached input",
  output: "Output",
  cache_read: "Cache read",
  cache_write_5m: "Cache write · 5 min",
  cache_write_1h: "Cache write · 1 hour",
  missing_usage: "Incomplete usage",
  model_unverified: "Model mapping not verified",
  unsupported_billing: "Billing method not supported for comparison",
  pending_settlement: "Settling",
  missing_price_history: "Historical official price missing",
  unsupported_funding: "Funding source needs reconciliation",
};
const tw: Copy = {
  title: "這筆用量，省了多少",
  official: "官網同用量估算",
  actual: "野菜實際扣費",
  saved: "預計節省",
  more: "高於官網估算",
  same: "與官網估算持平",
  unavailable: "尚未接通帳單",
  unavailableBody:
    "帳單接通後，這裡會按相同模型和用量比較費用。目前還沒有可核對的資料。",
  invalid: "暫時無法核對費用",
  invalidBody: "這份費用明細不完整或金額不一致，暫不顯示比較結果。",
  expired: "費用資訊已過期",
  expiredBody: "需要重新取得帳單後，才能繼續顯示費用比較。",
  none: "尚無可比較的用量",
  noneBody: "所選範圍內還沒有資料完整的已結算紀錄。",
  method: "如何計算",
  methodBody:
    "使用同一筆用量當時的官網 API 價格，分別計算輸入、輸出和快取費用，再與野菜帳單的最終扣費比較。美元參考價按 6.75 換算，實際扣費不重複換算。",
  estimate:
    "官網金額為相同模型、用量及快取條件下的估算，不是官網實際帳單。實際扣費指餘額扣減，不等同於儲值時支付的現金。",
  missing: "資料不足的用量不計入節省金額；方案、贈送及其他計費方式需分別核對。",
  coverage: "已納入",
  requests: "筆",
  excluded: "未納入比較的扣費",
  pending: "尚有待結算紀錄",
  details: "逐筆明細",
  request: "記錄編號",
  requestedAt: "使用時間",
  rounding:
    "分項費用及每筆美元換算先四捨五入到小數點後 6 位，再彙總；頁面金額保留 2 位。節省比例 =（官網估算 − 實際扣費）÷ 官網估算，使用未取整的彙總金額計算。",
  source: "官網來源",
  version: "價格版本",
  fxVersion: "匯率版本",
  model: "模型 ID",
  officialModel: "官網模型",
  conditions: "適用條件",
  qty: "用量",
  rate: "每百萬 token 單價",
  amount: "官網分項費用",
  total: "官網原幣合計",
  currency: "幣別",
  period: "統計範圍（本機時區）",
  to: "至",
  effective: "價格生效時間",
  checked: "價格核對時間",
  input: "一般輸入",
  output: "輸出",
  cache_read: "快取讀取",
  cache_write_5m: "快取寫入 · 5 分鐘",
  cache_write_1h: "快取寫入 · 1 小時",
  missing_usage: "缺少完整用量",
  model_unverified: "模型尚無法對應",
  unsupported_billing: "此計費方式尚未支援比較",
  pending_settlement: "結算中",
  missing_price_history: "缺少當時的官網價格",
  unsupported_funding: "需要分別核對資金來源",
};
const ja: Copy = {
  title: "同じ使用量で料金を比較",
  official: "公式料金での概算",
  actual: "野菜APIの実際の請求額",
  saved: "推定節約額",
  more: "公式料金の概算を上回る額",
  same: "公式料金の概算と同額",
  unavailable: "請求情報は未接続です",
  unavailableBody:
    "接続後、同じモデルと使用量で費用を比較できます。現在は照合できる請求情報がありません。",
  invalid: "料金を確認できません",
  invalidBody:
    "明細が不足しているか、金額が一致しないため比較を表示できません。",
  expired: "料金情報の有効期限が切れました",
  expiredBody: "請求情報を再取得してから比較を表示してください。",
  none: "比較できる使用量がありません",
  noneBody: "この期間には料金情報の揃った精算済みの記録がありません。",
  method: "計算方法",
  methodBody:
    "利用時点の公式API料金で入力、出力、キャッシュを別々に計算し、実際の精算額と比較します。米ドルの参考料金は固定レート6.75で換算します。実際の請求額は再換算しません。",
  estimate:
    "公式料金は同じモデル、使用量、キャッシュ条件を仮定した概算で、実際の公式請求書ではありません。請求額は残高からの差引額で、チャージ時の現金支払額とは異なります。",
  missing:
    "情報不足の記録は節約額に含めません。プラン、付与クレジットなどは別途照合が必要です。",
  coverage: "対象",
  requests: "件",
  excluded: "比較対象外の確認済み請求額",
  pending: "精算中の記録があります",
  details: "利用明細",
  request: "記録 ID",
  requestedAt: "利用日時",
  rounding:
    "各項目と各リクエストの米ドル換算を小数点以下6桁に四捨五入して合計し、画面には2桁で表示します。節約率 =（公式見積額 − 実際の請求額）÷ 公式見積額。表示用の丸め前の合計で計算します。",
  source: "公式の出典",
  version: "料金の版",
  fxVersion: "換算レートの版",
  model: "モデルID",
  officialModel: "公式モデル",
  conditions: "適用条件",
  qty: "使用量",
  rate: "100万トークンあたり",
  amount: "公式料金の内訳",
  total: "元の通貨での公式合計",
  currency: "通貨",
  period: "集計期間（現地時間）",
  to: "〜",
  effective: "料金の適用開始",
  checked: "料金の確認日時",
  input: "通常の入力",
  output: "出力",
  cache_read: "キャッシュ読込",
  cache_write_5m: "キャッシュ書込 · 5分",
  cache_write_1h: "キャッシュ書込 · 1時間",
  missing_usage: "使用量の情報不足",
  model_unverified: "モデルの対応が未確認",
  unsupported_billing: "この課金方式は比較未対応",
  pending_settlement: "精算中",
  missing_price_history: "当時の公式料金が不明",
  unsupported_funding: "支払原資の照合が必要",
};
export const comparisonCopies = { zh, en, "zh-TW": tw, ja };
export function useComparisonCopy(): Copy {
  const { i18n } = useTranslation();
  const language = i18n.resolvedLanguage ?? i18n.language;
  return (
    comparisonCopies[language as keyof typeof comparisonCopies] ??
    (language.startsWith("zh") ? zh : en)
  );
}
